{{ if .Values.createExampleSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-credentials
  labels:
    {{- include "garmin-grafana.labels" . | nindent 4 }}
type: Opaque
stringData:
  INFLUXDB_USERNAME: admin
  INFLUXDB_PASSWORD: password
  INFLUXDB_ADMIN_USER: admin
  INFLUXDB_ADMIN_PASSWORD: password
  GARMINCONNECT_EMAIL: example@example.com
  GARMINCONNECT_BASE64_PASSWORD: password
{{- end}}
